export const CHECK_USER_EXISTS_START = 'CHECK_USER_EXISTS_START';
export const CHECK_USER_EXISTS_SUCCESS = 'CHECK_USER_EXISTS_SUCCESS';
export const CHECK_USER_EXISTS_ERROR = 'CHECK_USER_EXISTS_ERROR';
