export const SET_NEW_PASSWORD_START = 'SET_NEW_PASSWORD_START';
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_ERROR = 'SET_NEW_PASSWORD_ERROR';
export const CLEAR_SET_NEW_PASSWORD_SUCCESS =
  'CLEAR_SET_NEW_PASSWORD_SUCCESS';
